DROP TABLE IF EXISTS orders_products;
DROP TABLE IF EXISTS carts_products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS app_users;

CREATE TABLE IF NOT EXISTS products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(2550)                           NOT NULL,
    image       VARCHAR(2550)                           NOT NULL,
    price       DOUBLE PRECISION                         NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS carts
(
    cart_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    created_on  TIMESTAMP WITH TIME ZONE                NOT NULL,
    app_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (cart_id),
    FOREIGN KEY (app_user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    created_on TIMESTAMP WITH TIME ZONE                NOT NULL,
    app_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    FOREIGN KEY (app_user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS carts_products
(
    cart_id    BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INTEGER CHECK (quantity > 0),
    CONSTRAINT pk_carts_products PRIMARY KEY (cart_id, product_id),
    FOREIGN KEY (cart_id) REFERENCES carts (cart_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders_products
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INTEGER CHECK (quantity > 0),
    CONSTRAINT pk_orders_products PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

INSERT INTO products (name, description, image, price)
VALUES ('Смартфон Galaxy S24', 'Флагманский смартфон с мощной камерой и дисплеем 120 Гц.', '/images/mob.jpg', 89999.00),
       ('Ноутбук MacBook Pro', 'Мощный ноутбук с процессором M3 Pro и 16 ГБ оперативной памяти.', '/images/nout.jpg',
        229999.00),
       ('Игровая приставка PlayStation 5', 'Консоль нового поколения с поддержкой 4K и SSD.', '/images/other.jpg',
        57999.00),
       ('Телевизор Samsung 55"', 'Современный 4K телевизор с технологией QLED.', '/images/other.jpg', 79999.00),
       ('Беспроводные наушники AirPods Pro', 'Шумоподавление и пространственный звук.', '/images/other.jpg', 24999.00),
       ('Умные часы Apple Watch Series 9', 'Трекинг здоровья и поддержка Apple Pay.', '/images/other.jpg', 42999.00),
       ('Планшет iPad Pro 12.9"', 'Мощный планшет для работы и творчества.', '/images/mob.jpg', 119999.00),
       ('Электронная книга Kindle Paperwhite', 'Читалка с экраном E-Ink и подсветкой.', '/images/mob.jpg', 12999.00),
       ('Кофемашина DeLonghi', 'Автоматическая кофемашина для идеального эспрессо.', '/images/other.jpg', 45999.00),
       ('Робот-пылесос Xiaomi', 'Умный пылесос с навигацией и управлением через приложение.', '/images/other.jpg',
        32999.00),
       ('Фитнес-браслет Xiaomi Mi Band 8', 'Умный браслет с мониторингом здоровья.', '/images/other.jpg', 4999.00),
       ('Микроволновая печь LG', 'Микроволновка с грилем и авторазморозкой.', '/images/other.jpg', 15999.00),
       ('Холодильник Bosch', 'Двухкамерный холодильник с системой No Frost.', '/images/other.jpg', 79999.00),
       ('Пылесос Dyson V15', 'Мощный беспроводной пылесос с датчиком пыли.', '/images/other.jpg', 65999.00),
       ('Блендер Philips', 'Кухонный блендер для приготовления смузи и супов.', '/images/other.jpg', 8999.00),
       ('Стиральная машина Samsung', 'Стиральная машина с функцией Eco Bubble.', '/images/other.jpg', 59999.00),
       ('Электросамокат Ninebot', 'Лёгкий и быстрый электросамокат для города.', '/images/other.jpg', 44999.00),
       ('Монитор LG 27"', '4K IPS-монитор с высокой цветопередачей.', '/images/other.jpg', 37999.00),
       ('Механическая клавиатура Razer', 'Игровая клавиатура с RGB-подсветкой.', '/images/other.jpg', 15999.00),
       ('Беспроводная мышь Logitech', 'Эргономичная мышь с высоким DPI.', '/images/other.jpg', 7999.00),
       ('Наушники Sony WH-1000XM5', 'Флагманские наушники с лучшим шумоподавлением.', '/images/other.jpg', 34999.00),
       ('Графический планшет Wacom', 'Идеален для художников и дизайнеров.', '/images/mob.jpg', 22999.00),
       ('Игровое кресло DXRacer', 'Эргономичное кресло для комфортных игровых сессий.', '/images/other.jpg', 29999.00),
       ('Электрогриль Tefal', 'Гриль для приготовления мяса и овощей.', '/images/other.jpg', 17999.00),
       ('Проектор Epson', 'Яркий и чёткий проектор для домашнего кинотеатра.', '/images/other.jpg', 69999.00);

INSERT INTO app_users(username, password)
VALUES ('test', 'test');

INSERT INTO carts (created_on, app_user_id)
VALUES (CURRENT_TIMESTAMP, 1);