version: '3.8'
services:
  shop-api:
    build: api
    container_name: api_container
    ports:
      - "9090:9090"
    depends_on:
      - shop-db
      - shop-redis
    volumes:
      - ./uploads/images:/uploads/images
    environment:
      - DB_NAME=shop
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=12345
      - DB_HOST=shop-db
      - DB_PORT=5432
  shop-view:
    build: view
    container_name: view_container
    ports:
      - "8080:8080"
    depends_on:
      - shop-api
  shop-db:
    container_name: api_db_container
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=12345
  shop-redis:
    container_name: api_redis_container
    image: redis:8.0-M04-bookworm
    ports:
      - "6379:6379"
  payment-db:
    container_name: payment_db_container
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
  payment:
    build: payment
    container_name: payment_container
    ports:
      - "9091:9091"
    depends_on:
      - payment-db
    environment:
      - DB_NAME=payment
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - DB_HOST=payment-db
      - DB_PORT=5432