version: '3.8'
services:
  shop-api:
    build: api
    container_name: api_container
    ports:
      - "9090:9090"
    depends_on:
      shop-db:
        condition: service_started
      shop-redis:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      - ./uploads/images:/uploads/images
    environment:
      - DB_NAME=shop
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=12345
      - DB_HOST=shop-db
      - DB_PORT=5432
  shop-view:
    build: view
    container_name: view_container
    ports:
      - "8080:8080"
    depends_on:
      keycloak:
        condition: service_healthy
      shop-api:
        condition: service_started
  shop-db:
    container_name: api_db_container
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=12345
  shop-redis:
    container_name: api_redis_container
    image: redis:8.0-M04-bookworm
    ports:
      - "6379:6379"
  payment-db:
    container_name: payment_db_container
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
  payment:
    build: payment
    container_name: payment_container
    ports:
      - "9091:9091"
    depends_on:
      - payment-db
      - keycloak
    environment:
      - DB_NAME=payment
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - DB_HOST=payment-db
      - DB_PORT=5432
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 4s