server:
  port: 9090
spring:
  r2dbc:
    url: r2dbc:postgresql://shop-db:5432/shop
    username: shopuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
