server:
  port: 9090
spring:
  r2dbc:
    url: r2dbc:postgresql://shop-db:5432/shop
    username: shopuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  data:
    redis:
      host: shop-redis
      port: 6379
  cache:
    redis:
      time-to-live: 60s
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          api:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: api-client
            client-secret: c0BAodfWd5LDtVOd70vSz7dtegfnzhou
            scope: profile
            clientAuthenticationMethod: client_secret_post
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master