CREATE TABLE IF NOT EXISTS products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(2550)                           NOT NULL,
    image       VARCHAR(2550)                           NOT NULL,
    price       DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS carts
(
    cart_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    created_on TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    created_on TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS carts_products
(
    cart_id    BIGINT                                  NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    quantity INTEGER CHECK (quantity > 0),
    CONSTRAINT pk_carts_products PRIMARY KEY (cart_id, product_id),
    FOREIGN KEY (cart_id) REFERENCES carts (cart_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders_products
(
    order_id    BIGINT                                  NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    quantity INTEGER CHECK (quantity > 0),
    CONSTRAINT pk_orders_products PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);