spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          view:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: view-client
            client-secret: TlB3tuyNfcaCNKXSZ156gFEAUQWVEtdU
            scope: profile
            clientAuthenticationMethod: client_secret_post