DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    name    VARCHAR(255)                            NOT NULL,
    balance DECIMAL(10, 2) CHECK (balance >= 0)     NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO users (name, balance)
VALUES ('Test User', 300000.00);